language: node_js
node_js:
- '6'
env:
  matrix:
  - TRAVIS_NODE_VERSION="6.3"
install:
- npm install
cache:
  directories:
  - node_modules
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIPKLFWX5TZYVHIFA
  secret_access_key:
    secure: dNIZ5ONeK8i3+ElM7BWk1y3hugYz35L9dSVg1EkakroaAAyyFgxpTjGmKnhdHdE+YZzr/vVbwO8nblef3BA7zn/ipvwQYvdCuyO6A3EAPd1N7PNHaVrzEbKXS1uPFmHzzMEYjmDPP12jt+YoRu4QreDP3qUGylOC7x6yo2FcnQi6WGsBClAKMUrnF0dsK03UbM8YzHFu1V4HaHI+xhGFvoJRALCcT21qrPZJ/CGx5KERbTr6/uxSUEdGIPS4KTplw3p7s3UwJPdI4zEaB8t17wfOpN0iHDTaNzw/+YgsSExd2ICJ9G4S9T8BnwlUH8+tc7OEeg91c8bZNDU7rbs7ZOXI48SDGIaKfRRUtCCvcnQvqC0iB4t+lhMtUUb215xtAL80hpYGa016qTF7O4m+X/ZVqfFSYLjdrdfSLsFKiEh7v6O/OLlOKiklQAdwt/AuxKCI5cJiQgZ5KkXDkjleENNrZSs4NrdnhYcMhFm+HmapnxhVRlbg3R2ASQWtV/SdMbiKVi1NW65jM7weAaOeDB0iJF1POcyZWMRICtiXfC2Z0a4tvGUetSwXK42zIVwUDvVMrWoinEDgnLL/eyjA4gjmU/RkqPqI81mPWWSlOo142zRVYl6LI5rECUel2qmVL1H25rmQj3336zehk7kc6YgxS0OUzKpo57KvoAnFHa0=
  region: us-east-2
  app: flickpick
  env: fliq
  bucket_name: elasticbeanstalk-us-east-2-088432678416
  on:
    repo: binary100/fliq
    branch: dev
